name = "SoleLogics"
uuid = "b002da8f-3cb3-4d91-bbe3-2953433912b5"
authors = ["Mauro MILELLA", "Giovanni PAGLIARINI", "Eduard I. STAN"]
version = "0.2.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReadableRegex = "cbbcb084-453d-4c4c-b292-e315607ba6a4"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SoleBase = "4475fa32-7023-44a0-aa70-4813b230e492"

[compat]
DataStructures = "0.18"
Dictionaries = "0.3"
IterTools = "1"
Lazy = "0.15"
Lazy = "0.15"
NamedArrays = "0.9"
ReadableRegex = "0.3"
Reexport = "1"
Revise = "3"
SoleBase = "0.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
