name = "SoleLogics"
uuid = "b002da8f-3cb3-4d91-bbe3-2953433912b5"
authors = ["Eduard I. STAN", "Milella MAURO", "Giovanni PAGLIARINI"]
version = "0.1.0"

[deps]
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SoleAlphabets = "bc461207-1577-452f-bfcc-57c11e9f51b7"
SoleTraits = "f0cd7361-857b-4e5b-8aae-3a26fab9cfa9"
SoleWorlds = "d5f91e23-4e14-4856-a67b-b38735209aab"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
